import type { MarketplaceListingAdmin } from "./types";

const placeholderImage = (seed: number) =>
  `https://picsum.photos/seed/cityfarm-market-${seed}/720/540`;

export const marketplaceListings: MarketplaceListingAdmin[] = [
  {
    id: "listing-401",
    title: "Rau mui - harvest sang nay",
    productLabel: "Herbs",
    seller: { id: "seller-01", name: "Mai Linh", verifiedGrower: true, district: "District 7" },
    pickupDistrict: "District 7",
    pickupCity: "Ho Chi Minh City",
    quantityText: "3.5 kg",
    priceText: "₫180.000 / kg",
    createdAtLabel: "11:08",
    expiresAtLabel: "In 2 days",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    documentedDays: 18,
    imageUrl: placeholderImage(41),
    notes: "Pickup after 18:00, bring your own bag.",
    quality: { photoScore: 86, descriptionScore: 74, documentationScore: 82, flags: 0 },
  },
  {
    id: "listing-402",
    title: "Xa lach thuy canh",
    productLabel: "Leafy greens",
    seller: { id: "seller-02", name: "Vu Hoang", verifiedGrower: false, district: "Binh Thanh" },
    pickupDistrict: "Binh Thanh",
    pickupCity: "Ho Chi Minh City",
    quantityText: "4 khay",
    priceText: "₫55.000 / khay",
    createdAtLabel: "10:42",
    expiresAtLabel: "In 1 day",
    status: "ACTIVE",
    verificationStatus: "PENDING",
    documentedDays: 6,
    imageUrl: placeholderImage(42),
    notes: "Anh cover hoi toi, can upload lai.",
    quality: { photoScore: 52, descriptionScore: 61, documentationScore: 45, flags: 2 },
  },
  {
    id: "listing-403",
    title: "Ca chua cherry (batch 2)",
    productLabel: "Fruits",
    seller: { id: "seller-03", name: "Nguyen Thanh", verifiedGrower: true, district: "Thu Duc" },
    pickupDistrict: "Thu Duc",
    pickupCity: "Ho Chi Minh City",
    quantityText: "2.1 kg",
    priceText: "₫120.000 / kg",
    createdAtLabel: "09:58",
    expiresAtLabel: "In 5 days",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    documentedDays: 21,
    imageUrl: placeholderImage(43),
    quality: { photoScore: 88, descriptionScore: 76, documentationScore: 90, flags: 0 },
  },
  {
    id: "listing-404",
    title: "Rau muong - garden share",
    productLabel: "Leafy greens",
    seller: { id: "seller-04", name: "Le Minh Anh", verifiedGrower: false, district: "Go Vap" },
    pickupDistrict: "Go Vap",
    pickupCity: "Ho Chi Minh City",
    quantityText: "1.2 kg",
    priceText: "₫75.000 / kg",
    createdAtLabel: "Yesterday",
    expiresAtLabel: "Today",
    status: "EXPIRED",
    verificationStatus: "NONE",
    documentedDays: 3,
    imageUrl: placeholderImage(44),
    quality: { photoScore: 49, descriptionScore: 44, documentationScore: 32, flags: 3 },
  },
  {
    id: "listing-405",
    title: "Sa lach xoong - mini batch",
    productLabel: "Herbs",
    seller: { id: "seller-05", name: "Pham Nhu Quynh", verifiedGrower: true, district: "District 1" },
    pickupDistrict: "District 1",
    pickupCity: "Ho Chi Minh City",
    quantityText: "900 g",
    priceText: "₫95.000 / batch",
    createdAtLabel: "2 days ago",
    expiresAtLabel: "In 6 days",
    status: "DRAFT",
    verificationStatus: "PENDING",
    documentedDays: 9,
    imageUrl: placeholderImage(45),
    notes: "Draft listing, waiting for seller note.",
    quality: { photoScore: 70, descriptionScore: 58, documentationScore: 66, flags: 1 },
  },
  {
    id: "listing-406",
    title: "Dua leo - thu hoach",
    productLabel: "Fruits",
    seller: { id: "seller-06", name: "Tran Gia Huy", verifiedGrower: true, district: "District 7" },
    pickupDistrict: "District 7",
    pickupCity: "Ho Chi Minh City",
    quantityText: "3 kg",
    priceText: "₫65.000 / kg",
    createdAtLabel: "3 days ago",
    expiresAtLabel: "In 4 days",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    documentedDays: 15,
    imageUrl: placeholderImage(46),
    quality: { photoScore: 84, descriptionScore: 69, documentationScore: 80, flags: 0 },
  },
];

