import type { FeedPost, MarketListing } from "./types";

export const feedPosts: FeedPost[] = [
  {
    id: "feed-1",
    type: "showcase",
    user: "Sarah Chen",
    location: "Dĩ An",
    caption: "My cherry tomatoes are finally setting fruit. The CITYFARM schedule is actually working.",
    image: "/cityfarm/img/tomato.png",
    likes: 24,
    comments: 5,
    time: "2h ago",
    tags: ["#TomatoSeason", "#UrbanHarvest"],
    isLiked: false,
  },
  {
    id: "feed-2",
    type: "question",
    user: "Mike Ross",
    location: "District 1",
    caption: "Mint leaves are yellowing at the tips. Too much sun or not enough water?",
    image: "/cityfarm/img/mint.png",
    likes: 12,
    comments: 8,
    time: "4h ago",
    tags: ["#HelpNeeded", "#Mint", "#Diagnosis"],
    isLiked: true,
  },
  {
    id: "feed-3",
    type: "plant-share",
    user: "David Nguyen",
    location: "District 3",
    caption: "Check out my lettuce at 64% growth. Sharing my log for anyone curious about a shaded kitchen setup.",
    sharedPlantId: "lettuce-02",
    likes: 18,
    comments: 4,
    time: "1h ago",
    tags: ["#PlantSharing", "#LettuceGrowing"],
    isLiked: false,
  },
  {
    id: "feed-4",
    type: "showcase",
    user: "Anh Tran",
    location: "Hoan Kiem",
    caption: "Just installed my new CITYFARM standing kit and the corner finally feels alive.",
    image: "/cityfarm/img/kit/standing.jpg",
    likes: 28,
    comments: 9,
    time: "9h ago",
    tags: ["#NewBeginner", "#GardenSetup"],
    isLiked: false,
  },
];

export const marketListings: MarketListing[] = [
  {
    id: "listing-101",
    seller: {
      name: "Grandma Mai",
      district: "District 3",
      verifiedGrower: true,
    },
    plant: "Organic Bok Choy",
    quantity: "500g",
    price: "30,000₫",
    imageUrl: "/cityfarm/img/lettuce.png",
    description: "Harvested this morning. No pesticides, grown in a compact balcony rack.",
    postedTime: "1h ago",
    plantingLogs: 45,
  },
  {
    id: "listing-102",
    seller: {
      name: "Tom's Balcony",
      district: "Thao Dien",
      verifiedGrower: false,
    },
    plant: "Thai Basil Bundle",
    quantity: "100g",
    price: "15,000₫",
    imageUrl: "/cityfarm/img/mint.png",
    description: "Spicy aroma, extra leaves from this week's prune.",
    postedTime: "3h ago",
    plantingLogs: 20,
  },
  {
    id: "listing-103",
    seller: {
      name: "Green Thumbs Co",
      district: "District 1",
      verifiedGrower: true,
    },
    plant: "Fresh Cherry Tomatoes",
    quantity: "300g",
    price: "25,000₫",
    imageUrl: "/cityfarm/img/tomato.png",
    description: "Sweet and juicy, documented from seedling to harvest.",
    postedTime: "2h ago",
    plantingLogs: 60,
  },
  {
    id: "listing-104",
    seller: {
      name: "Local Herbs",
      district: "District 7",
      verifiedGrower: false,
    },
    plant: "Green Onion Bundle",
    quantity: "250g",
    price: "12,000₫",
    imageUrl: "/cityfarm/img/onion.png",
    description: "Crisp, fresh, and ideal for same-day pickup.",
    postedTime: "7h ago",
    plantingLogs: 25,
  },
];
