import type { HomeStat, Plant, Reminder } from "./types";

export const plants: Plant[] = [
  {
    id: "tomato-01",
    name: "Cherry Tomato",
    type: "Vegetable",
    code: "CITYFARM-TOMATO-01",
    plantedDate: "2026-03-04",
    daysGrowing: 27,
    harvestDays: 60,
    health: "healthy",
    imageUrl: "/cityfarm/img/tomato.png",
    nextWatering: "Today, 5:00 PM",
    nextFertilizing: "In 3 days",
    progress: 48,
    zone: "East balcony rack",
    note: "Strong morning light and consistent stem support are keeping fruit clusters stable.",
    careHistory: [
      {
        id: "care-tomato-1",
        date: "2026-03-30",
        action: "Watered",
        time: "8:00 AM",
        aiDetection: "Soil moisture back to optimal range",
        status: "completed",
      },
      {
        id: "care-tomato-2",
        date: "2026-03-28",
        action: "Added support tie",
        time: "6:30 PM",
        aiDetection: "Stem angle corrected before flowering stage",
        status: "completed",
      },
    ],
    journal: [
      {
        id: "journal-tomato-1",
        date: "2026-03-31",
        photo: "/cityfarm/img/tomato.png",
        aiAnalysis: {
          health: "Healthy",
          leafColor: "Vibrant green",
          issues: "None detected",
          recommendation: "Keep the current watering rhythm and rotate the pot every 3 days.",
        },
      },
      {
        id: "journal-tomato-2",
        date: "2026-03-27",
        photo: "/cityfarm/img/tomato.png",
        aiAnalysis: {
          health: "Healthy",
          leafColor: "Balanced green",
          issues: "Mild canopy crowding",
          recommendation: "Prune two inner leaves to increase airflow.",
        },
      },
    ],
  },
  {
    id: "lettuce-02",
    name: "Green Lettuce",
    type: "Vegetable",
    code: "CITYFARM-LETTUCE-02",
    plantedDate: "2026-03-12",
    daysGrowing: 19,
    harvestDays: 35,
    health: "healthy",
    imageUrl: "/cityfarm/img/lettuce.png",
    nextWatering: "Tomorrow, 8:00 AM",
    nextFertilizing: "In 5 days",
    progress: 64,
    zone: "Kitchen window shelf",
    note: "Compact leafy growth makes it ideal for partial shade apartments in HCMC.",
    careHistory: [
      {
        id: "care-lettuce-1",
        date: "2026-03-30",
        action: "Misted leaves",
        time: "11:45 AM",
        aiDetection: "Leaf surface temperature reduced by 2°C",
        status: "completed",
      },
      {
        id: "care-lettuce-2",
        date: "2026-03-29",
        action: "Harvested outer leaves",
        time: "7:10 PM",
        aiDetection: "Canopy density balanced",
        status: "completed",
      },
    ],
    journal: [
      {
        id: "journal-lettuce-1",
        date: "2026-03-31",
        photo: "/cityfarm/img/lettuce.png",
        aiAnalysis: {
          health: "Healthy",
          leafColor: "Cool green",
          issues: "None detected",
          recommendation: "Harvest a small outer ring in 3-4 days for continued regrowth.",
        },
      },
    ],
  },
  {
    id: "mint-03",
    name: "Fresh Mint",
    type: "Herb",
    code: "CITYFARM-MINT-03",
    plantedDate: "2026-03-09",
    daysGrowing: 22,
    harvestDays: 45,
    health: "warning",
    imageUrl: "/cityfarm/img/mint.png",
    nextWatering: "Today, 3:00 PM",
    nextFertilizing: "Tomorrow",
    progress: 58,
    zone: "Hanging corner near skylight",
    note: "Tip yellowing suggests heat stress during early afternoon exposure.",
    careHistory: [
      {
        id: "care-mint-1",
        date: "2026-03-30",
        action: "Moved to softer shade",
        time: "1:15 PM",
        aiDetection: "Leaf stress score improving",
        status: "completed",
      },
      {
        id: "care-mint-2",
        date: "2026-03-28",
        action: "Bottom watering",
        time: "9:00 AM",
        aiDetection: "Moisture distribution normalized",
        status: "completed",
      },
    ],
    journal: [
      {
        id: "journal-mint-1",
        date: "2026-03-31",
        photo: "/cityfarm/img/mint.png",
        aiAnalysis: {
          health: "Warning",
          leafColor: "Slight yellowing",
          issues: "Heat stress on upper tips",
          recommendation: "Block direct sun from 13:00 to 15:00 and keep substrate evenly moist.",
        },
      },
    ],
  },
  {
    id: "onion-04",
    name: "Green Onion",
    type: "Herb",
    code: "CITYFARM-ONION-04",
    plantedDate: "2026-03-16",
    daysGrowing: 15,
    harvestDays: 28,
    health: "healthy",
    imageUrl: "/cityfarm/img/onion.png",
    nextWatering: "Tomorrow, 7:00 AM",
    nextFertilizing: "In 6 days",
    progress: 86,
    zone: "Window-edge mini trough",
    note: "Fast regrowth and high success rate make this a strong starter herb.",
    careHistory: [
      {
        id: "care-onion-1",
        date: "2026-03-30",
        action: "Trimmed first harvest",
        time: "6:20 PM",
        aiDetection: "Regrowth nodes remain healthy",
        status: "completed",
      },
    ],
    journal: [
      {
        id: "journal-onion-1",
        date: "2026-03-31",
        photo: "/cityfarm/img/onion.png",
        aiAnalysis: {
          health: "Healthy",
          leafColor: "Bright green",
          issues: "None detected",
          recommendation: "You can cut another small batch at the end of this week.",
        },
      },
    ],
  },
];

export const reminders: Reminder[] = [
  { id: "reminder-1", plant: "Cherry Tomato", action: "Water", time: "5:00 PM", icon: "water" },
  { id: "reminder-2", plant: "Fresh Mint", action: "Reduce harsh sun", time: "1:00 PM", icon: "sun" },
  { id: "reminder-3", plant: "Green Lettuce", action: "Check leaf density", time: "Tomorrow", icon: "check" },
];

export const homeStats: HomeStat[] = [
  { label: "Active Plants", value: `${plants.length}`, tone: "green" },
  { label: "Care Rate", value: "85%", tone: "blue" },
  { label: "HCMC Today", value: "28°C", tone: "amber" },
];
