import type { FeedPostRow } from "./types";

export const mockPosts: FeedPostRow[] = [
  {
    id: "post_581204",
    authorName: "Nguyen Thanh",
    authorDistrict: "Thu Duc",
    authorVerifiedGrower: true,
    createdAtLabel: "12 mins ago",
    postType: "PLANT_SHARE",
    caption:
      "Thu hoạch rau mầm sáng nay. Share log chăm cây + lịch watering. Mình sẽ bán bớt một phần harvest cho ai gần khu vực Thu Duc.",
    imageUrl: "",
    visibilityDistrict: "Thu Duc",
    signals: { likes: 14, comments: 6, reports: 3 },
    status: "NEEDS_REVIEW",
    riskNotes: ["Contains sales intent", "Multiple reports in 10 mins"],
  },
  {
    id: "post_581188",
    authorName: "Mai Linh",
    authorDistrict: "District 7",
    authorVerifiedGrower: false,
    createdAtLabel: "24 mins ago",
    postType: "SHOWCASE",
    caption:
      "Ban cong mua nay len form rat dep. Minh ghi lai soil recipe va timeline thay chau. Ai can minh share chi tiet nhe.",
    imageUrl: "placeholder",
    visibilityDistrict: "District 7",
    signals: { likes: 27, comments: 9, reports: 0 },
    status: "PUBLISHED",
    riskNotes: [],
  },
  {
    id: "post_581143",
    authorName: "Vu Hoang",
    authorDistrict: "Binh Thanh",
    authorVerifiedGrower: true,
    createdAtLabel: "39 mins ago",
    postType: "MARKETPLACE_SHARE",
    caption:
      "Con 4 khay xa lach thuy canh, pickup toi nay. Minh de gia hop ly cho khu Binh Thanh, ai can inbox.",
    imageUrl: "placeholder",
    visibilityDistrict: "Binh Thanh",
    signals: { likes: 11, comments: 3, reports: 1 },
    status: "FLAGGED",
    riskNotes: ["Sales post without listing link", "Asset quality needs review"],
  },
  {
    id: "post_581055",
    authorName: "Phan Vy",
    authorDistrict: "Go Vap",
    authorVerifiedGrower: false,
    createdAtLabel: "1 hr ago",
    postType: "QUESTION",
    caption:
      "Cay bac ha cua minh bi la vang nhe. Minh watering 2 ngay/lon. Co ai gap truong hop tuong tu va co goi y cai thien khong?",
    imageUrl: "",
    visibilityDistrict: "Go Vap",
    signals: { likes: 8, comments: 11, reports: 0 },
    status: "PUBLISHED",
    riskNotes: [],
  },
  {
    id: "post_580991",
    authorName: "Dao Quoc",
    authorDistrict: "Thu Duc",
    authorVerifiedGrower: false,
    createdAtLabel: "2 hrs ago",
    postType: "HARVEST_UPDATE",
    caption:
      "Update dot thu hoach dau tay. Minh se chia se them ve light score va cach xoay chau de cay ra hoa deu.",
    imageUrl: "placeholder",
    visibilityDistrict: "Thu Duc",
    signals: { likes: 19, comments: 4, reports: 0 },
    status: "PUBLISHED",
    riskNotes: [],
  },
  {
    id: "post_580900",
    authorName: "Minh Chau",
    authorDistrict: "District 7",
    authorVerifiedGrower: true,
    createdAtLabel: "3 hrs ago",
    postType: "SHOWCASE",
    caption:
      "Anh nay minh chup luc sang som, co ve bi trung voi anh truoc do minh up. Neu vi pham rule thi minh se chinh sua.",
    imageUrl: "placeholder",
    visibilityDistrict: "District 7",
    signals: { likes: 4, comments: 1, reports: 2 },
    status: "FLAGGED",
    riskNotes: ["Possible duplicate image", "2 reports from same district"],
  },
  {
    id: "post_580844",
    authorName: "An Nguyen",
    authorDistrict: "Binh Thanh",
    authorVerifiedGrower: false,
    createdAtLabel: "4 hrs ago",
    postType: "QUESTION",
    caption:
      "Mua nay troi nong, minh co nen doi lich watering sang sang som khong? Neu watering toi thi co bi nam khong?",
    imageUrl: "",
    visibilityDistrict: "Binh Thanh",
    signals: { likes: 6, comments: 7, reports: 0 },
    status: "PUBLISHED",
    riskNotes: [],
  },
] as const;

export const mockDistricts = ["Thu Duc", "District 7", "Binh Thanh", "Go Vap"] as const;
